import creativeAgency from "../image/works/creative-agency.png";
import creative_thumbnail from '../image/works/creative_thumbnail.png';
import voleenterThumbnail from '../image/works/voleenter_works_thumbnail.jpg';
import voleenterFullPhoto from '../image/works/voleenter_work_full.png';
import netflixClone from '../image/works/netflix-clone.png';
import netflixLandingPage from '../image/works/netflix-landing-page.png';

export const fakeData = [
  {
    title: "Creative Agency",
    sub_title: "This is sub title for the createive website.",
    live_link: "https://creative-agency-8d8f6.web.app/",
    github_Link: [{ title: 'Frontend Code', url: "https://github.com/mamunur13525/Creative_Agency" }],
    thumbail_image: creative_thumbnail,
    full_photo: creativeAgency,
    images: "https://source.unsplash.com/aJeH0KcFkuc/400x300",
    category: 'React',
    technology_used: [
      "Javascript",
      "React",
      "MongoDB",
      "Node.js",
      "Express",
      "HTML5",
      "CSS3",
    ],
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo dicta a reiciendis quisquam blanditiis voluptate culpa sint saepe doloribus? Sint repudiandae enim praesentium dignissimos veniam soluta laboriosam temporibus nobis explicabo.",
  },
  {
    title: "Voleenter Works",
    sub_title: "This is sub title for the createive website.",
    live_link: "https://voleenter-works.netlify.app/",
    github_Link: [{ title: 'Frontend Code', url: "https://github.com/mamunur13525/volenteer_works" }],
    thumbail_image: voleenterThumbnail,
    full_photo: voleenterFullPhoto,
    images: "https://source.unsplash.com/aJeH0KcFkuc/400x300",
    category: 'firebase',
    technology_used: [
      "Javascript",
      "React",
      "MongoDB",
      "Node.js",
      "Express",
      "HTML5",
      "CSS3",
    ],
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo dicta a reiciendis quisquam blanditiis voluptate culpa sint saepe doloribus? Sint repudiandae enim praesentium dignissimos veniam soluta laboriosam temporibus nobis explicabo.",
  },
  {
    title: "Netflix Clone",
    sub_title: "This is sub title for the createive website.",
    live_link: "https://netflix-clone-mamundev.netlify.app",
    github_Link: [{ title: 'Frontend Code', url: "https://github.com/mamunur13525/Netflix-Clone-With-React" }],
    thumbail_image: netflixClone,
    full_photo: netflixLandingPage,
    images: "https://source.unsplash.com/aJeH0KcFkuc/400x300",
    category: 'React',
    technology_used: [
      "Javascript",
      "React",
      "API",
      "Express",
      "HTML5",
      "CSS3",
    ],
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo dicta a reiciendis quisquam blanditiis voluptate culpa sint saepe doloribus? Sint repudiandae enim praesentium dignissimos veniam soluta laboriosam temporibus nobis explicabo.",
  },
  {
    title: "Course Blog Site",
    sub_title: "This is sub title for the createive website.",
    live_link: "https://creative-agency-8d8f6.web.app/",
    github_Link: [{ title: 'Frontend Code', url: "https://github.com/mamunur13525/free_course_front" }, { title: 'Backend Code', url: 'https://github.com/mamunur13525/FreeCourseBackend.git' }],
    thumbail_image: creative_thumbnail,
    full_photo: creativeAgency,
    images: "https://source.unsplash.com/aJeH0KcFkuc/400x300",
    category: 'React',
    technology_used: [
      "Javascript",
      "React",
      "MongoDB",
      "Node.js",
      "Express",
      "HTML5",
      "CSS3",
    ],
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo dicta a reiciendis quisquam blanditiis voluptate culpa sint saepe doloribus? Sint repudiandae enim praesentium dignissimos veniam soluta laboriosam temporibus nobis explicabo.",
  },
  {
    title: "Creative Agency",
    sub_title: "This is sub title for the createive website.",
    live_link: "https://creative-agency-8d8f6.web.app/",
    github_Link: [{ title: 'Frontend Code', url: "https://github.com/mamunur13525/Creative_Agency" }],
    thumbail_image: creative_thumbnail,
    full_photo: creativeAgency,
    images: "https://source.unsplash.com/aJeH0KcFkuc/400x300",
    category: 'React',
    technology_used: [
      "Javascript",
      "React",
      "MongoDB",
      "Node.js",
      "Express",
      "HTML5",
      "CSS3",
    ],
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo dicta a reiciendis quisquam blanditiis voluptate culpa sint saepe doloribus? Sint repudiandae enim praesentium dignissimos veniam soluta laboriosam temporibus nobis explicabo.",
  },
  {
    title: "Creative Agency",
    sub_title: "This is sub title for the createive website.",
    live_link: "https://creative-agency-8d8f6.web.app/",
    github_Link: [{ title: 'Frontend Code', url: "https://github.com/mamunur13525/Creative_Agency" }],
    thumbail_image: creative_thumbnail,
    full_photo: creativeAgency,
    images: "https://source.unsplash.com/aJeH0KcFkuc/400x300",
    category: 'React',
    technology_used: [
      "Javascript",
      "React",
      "MongoDB",
      "Node.js",
      "Express",
      "HTML5",
      "CSS3",
    ],
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo dicta a reiciendis quisquam blanditiis voluptate culpa sint saepe doloribus? Sint repudiandae enim praesentium dignissimos veniam soluta laboriosam temporibus nobis explicabo.",
  },
  {
    title: "Creative Agency",
    sub_title: "This is sub title for the createive website.",
    live_link: "https://creative-agency-8d8f6.web.app/",
    github_Link: [{ title: 'Frontend Code', url: "https://github.com/mamunur13525/Creative_Agency" }],
    thumbail_image: creative_thumbnail,
    full_photo: creativeAgency,
    images: "https://source.unsplash.com/aJeH0KcFkuc/400x300",
    category: 'React',
    technology_used: [
      "Javascript",
      "React",
      "MongoDB",
      "Node.js",
      "Express",
      "HTML5",
      "CSS3",
    ],
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo dicta a reiciendis quisquam blanditiis voluptate culpa sint saepe doloribus? Sint repudiandae enim praesentium dignissimos veniam soluta laboriosam temporibus nobis explicabo.",
  },
  {
    title: "Creative Agency",
    sub_title: "This is sub title for the createive website.",
    live_link: "https://creative-agency-8d8f6.web.app/",
    github_Link: [{ title: 'Frontend Code', url: "https://github.com/mamunur13525/Creative_Agency" }],
    thumbail_image: creative_thumbnail,
    full_photo: creativeAgency,
    images: "https://source.unsplash.com/aJeH0KcFkuc/400x300",
    category: 'React',
    technology_used: [
      "Javascript",
      "React",
      "MongoDB",
      "Node.js",
      "Express",
      "HTML5",
      "CSS3",
    ],
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo dicta a reiciendis quisquam blanditiis voluptate culpa sint saepe doloribus? Sint repudiandae enim praesentium dignissimos veniam soluta laboriosam temporibus nobis explicabo.",
  },
  {
    title: "Creative Agency",
    sub_title: "This is sub title for the createive website.",
    live_link: "https://creative-agency-8d8f6.web.app/",
    github_Link: [{ title: 'Frontend Code', url: "https://github.com/mamunur13525/Creative_Agency" }],
    thumbail_image: creative_thumbnail,
    full_photo: creativeAgency,
    images: "https://source.unsplash.com/aJeH0KcFkuc/400x300",
    category: 'React',
    technology_used: [
      "Javascript",
      "React",
      "MongoDB",
      "Node.js",
      "Express",
      "HTML5",
      "CSS3",
    ],
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo dicta a reiciendis quisquam blanditiis voluptate culpa sint saepe doloribus? Sint repudiandae enim praesentium dignissimos veniam soluta laboriosam temporibus nobis explicabo.",
  },
  {
    title: "Creative Agency",
    sub_title: "This is sub title for the createive website.",
    live_link: "https://creative-agency-8d8f6.web.app/",
    github_Link: [{ title: 'Frontend Code', url: "https://github.com/mamunur13525/Creative_Agency" }],
    thumbail_image: creative_thumbnail,
    full_photo: creativeAgency,
    images: "https://source.unsplash.com/aJeH0KcFkuc/400x300",
    category: 'React',
    technology_used: [
      "Javascript",
      "React",
      "MongoDB",
      "Node.js",
      "Express",
      "HTML5",
      "CSS3",
    ],
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo dicta a reiciendis quisquam blanditiis voluptate culpa sint saepe doloribus? Sint repudiandae enim praesentium dignissimos veniam soluta laboriosam temporibus nobis explicabo.",
  },
];
